# Generated by Django 5.1.6 on 2025-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='event',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
