# Generated by Django 5.1.6 on 2025-03-14 12:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
