# Generated by Django 5.1.6 on 2025-03-15 11:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dpw2txejq/image/upload/v1/events/default-event_zuhvve', max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
