# Generated by Django 5.1.6 on 2025-03-15 12:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_o0lbny', max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
